---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-of-life
  labels:
    name: gameoflife
    version: jdk8
spec:
  minReadySeconds: 5
  replicas: 3
  selector:
    matchLabels:
      name: game-of-life
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      name: game-of-life
      labels:
        app: gameoflife
        version: jdk8
    spec:
      containers:
        - image: 
          name: game-of-life
          ports:
            - containerPort: 8080
              protocol: TCP
                
      

