---
apiVersion: v1
kind: Service
metadata: 
  name: gameoflife-svc
  labels:
    app: gameoflife
spec:
  type: LoadBalancer
  selector:
    app: gameoflife
  ports:
    - name: gameoflife-webport
      port: 8080
      targetPort: 8080




#apiVersion: v1
#kind: Service
#metadata:
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
  name: nginx-elb
  labels:
    app: nginx
 #spec:
  #type: LoadBalancer
  #ports:
  #- name: "http"
    #port: 80
   # targetPort: 80
  #selector:
    #app: nginx



---
apiVersion: v1
kind: Pod
metadata: 
  name: nginx
  labels:
    name: nginx
spec:
  containers:
    - image: nginx:1.23
      name: nginx
      ports: 
        - containerPort: 80
          protocol: TCP
      

