---
apiVersion: v1
kind: Service
metadata: 
  name: MysqlSVC
  labels:
    db: mysql
    type: service
spec:
  type: ClusterIP
  selector:
    db: mysql
  ports:
    - port: 3306
      name: MysqlPort
      targetPort: 3306
