---
apiVersion: v1
kind: Service
metadata: 
  name: openmrs-svc
  labels:
    app: openmrs
    type: service
spec:
  type: LoadBalancer
  selector:
    app: openmrs
  ports:
    - port: 8080
      name: openmrs-web-port
      targetPort: 8080
