---
apiVersion: v1
kind: Pod
metadata:
  name: restart-policy
spec:
  containers:
    - image: alpine:3
      name: restart-never
      command: 
        - sleep
        - "1d"
  restartPolicy: Never      