---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: storageclass
  labels:
    name: storageclass
provisioner: ebs.csi.aws.com
reclaimPolicy: Retain
allowVolumeExpansion: true
mountOptions:
  - debug
volumeBindingMode: Immediate
  

 