---
apiVersion: v1
kind: Service
metadata: 
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-path: /  
  name: nginx-svc
  labels:
    app: nginx
    type: service
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
    - port: 80
      name: nginx-web-port
      targetPort: 80
