---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    name: nginx
spec:
  minReadySeconds: 5
  replicas: 1
  selector:
    matchLabels:
      name: nginx
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      name: nginx
      labels:
        name: nginx
    spec:
      containers:
        - image: nginx:1.23 
          name: nginx
          ports:
            - containerPort: 80
              protocol: TCP
                
      

