---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  labels:
    app: nginx
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
    - name: nginx-webport
      port: 80


annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb 