---
apiVersion: v1
kind: Pod
metadata:
  name: 1st-pod
spec:
  containers:
    - image: nginx:1.23
      name: nginx
      ports:
        - containerPort: 80
          protocol: TCP
          name: nginx-port
    - image: jenkins/jenkins:jdk11
      name: jenkins
      ports:
        - containerPort: 8080
          protocol: TCP
          name: jenkins-port
    - image: alpine:3
      name: alpine
      command: 
        - sleep
        - "1d"            