---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: saleor-pvc
spec:
  storageClassName: ebs-sc
  accessModes:
    - ReadWriteOnce
  resources:   
    requests:
      storage: 1Gi      





