---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: saleor-2-pvc
  labels:
    app: saleor
spec:
  storageClassName: ebs-sc
  accessModes:
    - ReadWriteMany
  resources:   
    requests:
      storage: 1Gi      
      



